spring.application.name=cruscotto-oracle
server.port=8090

# Configurazione Oracle JDBC (sostituire con i tuoi valori)
spring.datasource.url=jdbc:oracle:thin:@prodalias:1521:prod
spring.datasource.username=ALER
spring.datasource.password=aler
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Pool connessioni
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Dashboard settings
app.logs.max-size=100
app.logs.persist.enabled=true
app.target-applications=ALER,ALER,ALER
app.default-application=ALER
app.output.folder=output
app.output.max-items=100

# Disabilita cache template in sviluppo
spring.thymeleaf.cache=false
